name: ci-cd-streamlit

on:
  push:
    branches:
      - master

jobs:
  package-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install streamlit

      - name: Package code
        run: zip -r code.zip .

      - name: Deploy code
        run: streamlit run https://github.com/adebayodeji/test_streamlit_app/blob/master/CICD_Test1.py --server.address https://localhost:8600 --server.port 8600 

