name: ci-cd-streamlit

on:
  push:
    branches:
      - master



jobs:
  package-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install streamlit

      - name: Deploy code
        env:
          SERVER_IP: localhost
          PORT: 8501
        run: |
          streamlit run https://github.com/adebayodeji/test_streamlit_app/blob/master/CICD_Test1.py --host=localhhost --port=8501
      - name: start local server
        run: |
          python -m http.server 8501

